const BACKEND = process.env.NEXT_PUBLIC_BACKEND_URL ?? 'http://localhost:3001';

export const AGENTS = [
  {
    id: 6,
    name: 'Camila Delacour',
    zone: 'Nacional',
    cities: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Santiago', 'Chapala', 'Mérida'],
    wa: '525662548748',
    photo: `${BACKEND}/imagenes/Agentes/Camila Delacour.png` as string | null,
    initials: 'CD',
    color: '#7C5CBF',
    languages: ['🇲🇽', '🇺🇸', '🇫🇷'],
    specialist: true,
  },
  {
    id: 1,
    name: 'Alicia Beneviento',
    zone: 'CDMX / Monterrey',
    cities: ['Ciudad de México', 'Monterrey'],
    wa: '525637835178',
    photo: `${BACKEND}/imagenes/Agentes/Alicia Beneviento.png` as string | null,
    initials: 'AB',
    color: '#C9A84C',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 2,
    name: 'Sofia Navarro',
    zone: 'CDMX',
    cities: ['Ciudad de México'],
    wa: '525572716417',
    photo: `${BACKEND}/imagenes/Agentes/Sofia Navarro.png` as string | null,
    initials: 'SN',
    color: '#A84C9C',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 7,
    name: 'Diego de la Madrid',
    zone: 'San Miguel / Guadalajara',
    cities: ['San Miguel de Allende', 'Guadalajara'],
    wa: '525521855541',
    photo: `${BACKEND}/imagenes/Agentes/Diego de la Madrid.png` as string | null,
    initials: 'DM',
    color: '#B45309',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 5,
    name: 'Daniela Villaseñor',
    zone: 'Monterrey / Santiago',
    cities: ['Monterrey', 'Santiago'],
    wa: '525529122887',
    photo: `${BACKEND}/imagenes/Agentes/Daniela Villaseñor.png` as string | null,
    initials: 'DV',
    color: '#9C4A6C',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 8,
    name: 'Isabella Salazar',
    zone: 'San Miguel / Guadalajara',
    cities: ['Guanajuato', 'San Miguel de Allende', 'Guadalajara'],
    wa: '525522551646',
    photo: `${BACKEND}/imagenes/Agentes/Isabella Salazar.png` as string | null,
    initials: 'IS',
    color: '#BE185D',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 3,
    name: 'Santiago Garcia',
    zone: 'Guadalajara / Puerto Vallarta',
    cities: ['Guadalajara', 'Chapala', 'Puerto Vallarta', 'Nuevo Vallarta'],
    wa: '525527087412',
    photo: `${BACKEND}/imagenes/Agentes/Santiago Garcia.png` as string | null,
    initials: 'SG',
    color: '#4A9C8A',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 9,
    name: 'Rafael Cervantes',
    zone: 'Cancún / Tulum',
    cities: ['Cancún', 'Tulum', 'Playa del Carmen'],
    wa: '525527105786',
    photo: null,
    initials: 'RC',
    color: '#0E7490',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 10,
    name: 'Alonso Ramírez',
    zone: 'Mérida / Playa del Carmen',
    cities: ['Mérida', 'Playa del Carmen'],
    wa: '525566264112',
    photo: null,
    initials: 'AR',
    color: '#0E7490',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
];

export const CAMILA = AGENTS[0];

export type Agent = typeof AGENTS[0];
