const BACKEND = process.env.NEXT_PUBLIC_BACKEND_URL ?? 'http://localhost:3001';

export const AGENTS = [
  {
    id: 6,
    name: 'Camila Delacour',
    zone: 'Nacional',
    cities: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Santiago', 'Chapala'],
    wa: '525563783517',
    photo: `${BACKEND}/imagenes/Agentes/Camila Delacour.png` as string | null,
    initials: 'CD',
    color: '#7C5CBF',
    languages: ['🇲🇽', '🇺🇸', '🇫🇷'],
    specialist: true,
  },
  {
    id: 1,
    name: 'Alicia Beneviento',
    zone: 'CDMX',
    cities: ['Ciudad de México'],
    wa: '525563783517',
    photo: `${BACKEND}/imagenes/Agentes/Alicia Beneviento.png` as string | null,
    initials: 'AB',
    color: '#C9A84C',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 2,
    name: 'Sofia Navarro',
    zone: 'CDMX',
    cities: ['Ciudad de México'],
    wa: '525662648748',
    photo: `${BACKEND}/imagenes/Agentes/Sofia Navarro.png` as string | null,
    initials: 'SN',
    color: '#A84C9C',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 5,
    name: 'Daniela Villaseñor',
    zone: 'Monterrey',
    cities: ['Monterrey', 'Santiago'],
    wa: '528123584598',
    photo: `${BACKEND}/imagenes/Agentes/Daniela Villaseñor.png` as string | null,
    initials: 'DV',
    color: '#9C4A6C',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 3,
    name: 'Santiago Garcia',
    zone: 'Guadalajara',
    cities: ['Guadalajara', 'Chapala'],
    wa: '523329599295',
    photo: `${BACKEND}/imagenes/Agentes/Santiago Garcia.png` as string | null,
    initials: 'SG',
    color: '#4A9C8A',
    languages: ['🇲🇽', '🇺🇸'],
    specialist: false,
  },
  {
    id: 4,
    name: 'Daniel Ortega',
    zone: 'Guadalajara',
    cities: ['Guadalajara', 'Chapala'],
    wa: '523329587681',
    photo: `${BACKEND}/imagenes/Agentes/Daniel Ortega.png` as string | null,
    initials: 'DO',
    color: '#4A6C9C',
    languages: ['🇲🇽', '🇺🇸', '🇧🇷'],
    specialist: false,
  },
];

export const CAMILA = AGENTS[0];

export type Agent = typeof AGENTS[0];
