const BACKEND = process.env.NEXT_PUBLIC_BACKEND_URL ?? 'http://localhost:3001';

export const AGENTS = [
  {
    id: 1,
    name: 'Camila Lefebvre',
    zone: 'Ciudad de México',
    cities: ['Ciudad de México'],
    wa: '525643232610',
    photo: `${BACKEND}/imagenes/Agentes/Camila Lefebvre.jpg` as string | null,
    initials: 'CL',
    color: '#7C5CBF',
    languages: ['MX', 'US', 'FR'],
    specialist: true,
  },
  {
    id: 2,
    name: 'Mariana Hernández',
    zone: 'Cancún / Tulum',
    cities: ['Cancún', 'Tulum'],
    wa: '525522551646',
    photo: `${BACKEND}/imagenes/Agentes/Mariana Hernandez.jpg` as string | null,
    initials: 'MH',
    color: '#0E7490',
    languages: ['MX', 'US'],
    specialist: false,
  },
  {
    id: 3,
    name: 'Ximena Hernández',
    zone: 'Playa del Carmen / Cancún',
    cities: ['Playa del Carmen', 'Cancún'],
    wa: '525663757704',
    photo: `${BACKEND}/imagenes/Agentes/Ximena Hernandez.jpg` as string | null,
    initials: 'XH',
    color: '#BE185D',
    languages: ['MX', 'US'],
    specialist: false,
  },
  {
    id: 4,
    name: 'Alejandro Pérez',
    zone: 'Puerto Vallarta / Nuevo Vallarta',
    cities: ['Puerto Vallarta', 'Nuevo Vallarta'],
    wa: '525521855541',
    photo: `${BACKEND}/imagenes/Agentes/Alejandro Perez.jpg` as string | null,
    initials: 'AP',
    color: '#B45309',
    languages: ['MX', 'US'],
    specialist: false,
  },
  {
    id: 5,
    name: 'Luciana Torres',
    zone: 'San Miguel de Allende',
    cities: ['San Miguel de Allende'],
    wa: '525527087412',
    photo: `${BACKEND}/imagenes/Agentes/Luciana Torres.jpg` as string | null,
    initials: 'LT',
    color: '#9C4A6C',
    languages: ['MX', 'US'],
    specialist: false,
  },
  {
    id: 6,
    name: 'Sebastián Reyes',
    zone: 'Guadalajara / Chapala',
    cities: ['Guadalajara', 'Chapala'],
    wa: '525527105786',
    photo: `${BACKEND}/imagenes/Agentes/Sebastian Reyes.jpg` as string | null,
    initials: 'SR',
    color: '#4A9C8A',
    languages: ['MX', 'US'],
    specialist: false,
  },
  {
    id: 7,
    name: 'Valentina Flores',
    zone: 'Monterrey / Santiago',
    cities: ['Monterrey', 'Santiago'],
    wa: '525662641121',
    photo: `${BACKEND}/imagenes/Agentes/Valentina Flores.jpg` as string | null,
    initials: 'VF',
    color: '#A84C9C',
    languages: ['MX', 'US'],
    specialist: false,
  },
  {
    id: 8,
    name: 'Ángel Morales',
    zone: 'Mérida',
    cities: ['Mérida'],
    wa: '525529122887',
    photo: `${BACKEND}/imagenes/Agentes/Angel Morales.jpg` as string | null,
    initials: 'AM',
    color: '#C9A84C',
    languages: ['MX', 'US'],
    specialist: false,
  },
];

export const CAMILA = AGENTS[0];

export type Agent = typeof AGENTS[0];